#!/bin/bash

set -euo pipefail

default_path() {
  if [ $OS = darwin ]; then
    default_path_darwin
  else
    echo $PATH
  fi
}

default_path_darwin() {
  # macOS adds a lot of crap to the $PATH that I really don't need.
  #
  # The com.apple.security.cryptexd directories don't even exist on any
  # system I've checked, nor do the /opt/pkg and /opt/pmk directories.
  #
  # I have removed the following directories, although I could consider
  # allowing them:
  #
  #   - /System/Cryptexes/App/usr/bin - contains safaridriver, which launches
  #     a Selenium driver for Safari that might be useful for local web dev
  #   - /Library/Apple/usr/bin - contains rvictl, which creates a virtual
  #     network interface to capture traffic from iOS devices and might
  #     also be useful for local iOS dev
  #
  # If I want to add these, remove
  #
  #   | egrep -v ^/System/Cryptexes \
  #   | fgrep -v /Library/Apple/usr/bin \
  #
  # from the pipeline below.

  echo $PATH \
    | tr : "\n" \
    | egrep -v ^/System/Cryptexes \
    | fgrep -v /Library/Apple/usr/bin \
    | fgrep -v com.apple.security.cryptexd \
    | egrep -v '^/opt/p(kg|mk)/env' \
    | tr "\n" :
}

brew_home() {
  if [ $(uname -m) = arm64 ]; then
    echo /opt/homebrew
  else
    echo /usr/local
  fi
}

brew_prefix() {
  echo "$(brew_home)/opt/$1"
}

brew_installed() {
  test -e $(brew_prefix $1)
}

macvim=''
docker=''
x11bin=''
whichbin=''
gettext=''
libpq=''
homebrew=$(brew_home)/bin

test -n "$(find ~/.docker/bin -type f -maxdepth 1)" && docker="${HOME}/.docker/bin"
test -d /Applications/MacVim.app/Contents/bin && macvim=/Applications/MacVim.app/Contents/bin
test -d /opt/X11/bin && x11bin=/opt/X11/bin

$(brew_installed gnu-which) && whichbin=$(brew_prefix gnu-which)/libexec/gnubin
$(brew_installed gettext) && gettext=$(brew_prefix gettext)/bin

# Nowadays I normally run Postgres in Docker, so I only install libpq
# to get access to the `psql` binary.
$(brew_installed libpq) && libpq=$(brew_prefix libpq)/bin

cat <<EOS | tr '\n' ':' | sed 's/:$//' | tr -s :
$XDG_BIN_HOME
$XDG_LIBEXEC_HOME/git
$macvim
$docker
$x11bin
$whichbin
$gettext
$libpq
$homebrew
$(default_path)
EOS
echo
