#!/bin/sh

# A poor-man's version of Mac OS X's excellent `brew` script.
# To use, create a symlink called "brew" from somewhere on
# your $PATH to this script.
#
# It is designed to provide some of the same basic functionality
# as `brew`, so that `brew` can be used in bash scripts even on
# systems that don't have Homebrew installed.
#
# It assumes that there is a /brew directory or symlink on the
# system, but will default to /usr/local in the absence of such
# a path.

function die {
  echo "$(basename $0): $2" 1>&2
  exit $1
}

function _prefix {
  if [ -d /brew ]; then
    echo $(readlink -f /brew)
  else
    echo '/usr/local'
  fi
}

function _list {
  if [ $# -eq 1 ]; then
    local pkg pkgd pkgv
    pkg=$1
    pkgd="$(_prefix)/Cellar/${pkg}"
    if [ -d "$pkgd" ]; then
      pkgv=$(ls -r "$(brew --prefix)/Cellar/${pkg}" | head -n 1)
      pkgd="$(brew --prefix)/Cellar/${pkg}/${pkgv}"
      tree "$pkgd"
    else
      die 2 "no such package: $pkg"
    fi
  else
    if [ -d "$(_prefix)/Cellar" ]; then
      find "$(_prefix)/Cellar" -maxdepth 2 -mindepth 2 -type d | cut -d / -f 8,9 | tr / ' ' | sort | column -t
    fi
  fi
}

case "$1" in
  --prefix)
    shift
    _prefix $*
    ;;
  ls)
    shift
    _list $*
    ;;
  *)
    die 1 'invalid arguments'
esac
